extends RefCounted
class_name HotNContent

const RULES := {
	"team_size": 3, "deck_size": 8, "copy_limit": 2, "hand_max": 10,
	"opening_hand": 5, "turn_draw": 2, "card_plays": 3,
	"redraws": 2, "moves": 1, "item_uses": 1,
	"impulse_max": 10, "items_max": 3,
}

const TYPES := {
	"BRUTO": {"MENTAL": 1.25, "PROJETIVO": 0.75},
	"TECNICO": {"PSICOLOGICO": 1.25, "QUIMICO": 0.75},
	"PSICOLOGICO": {"QUIMICO": 1.25, "BRUTO": 0.75},
	"MENTAL": {"PROJETIVO": 1.25, "TECNICO": 0.75},
	"PROJETIVO": {"TECNICO": 1.25, "PSICOLOGICO": 0.75},
	"QUIMICO": {"BRUTO": 1.25, "MENTAL": 0.75},
}

const HEROES := {
	"guerreiro": {"name": "Guerreiro", "hp": 40, "attack": 8, "power": 2, "armor": 3, "speed": 5, "type": "BRUTO", "sprite": "res://hero_fighter.png", "row": "front", "passive": "vanguarda", "playable": true, "pool": ["corte", "guarda", "investida", "contra", "furia", "golpe_largo", "preparo", "ruptura", "frenesi_aco", "martelo_pesado", "furia_totem", "corte_adj"], "cards": ["corte", "corte", "guarda", "guarda", "investida", "investida", "contra", "furia"]},
	"mago": {"name": "Mago", "hp": 26, "attack": 2, "power": 9, "armor": 1, "speed": 4, "type": "PROJETIVO", "sprite": "res://hero_wizard.png", "row": "back", "passive": "canalizar", "playable": true, "pool": ["raio", "barreira", "explosao", "runas", "tempestade", "centelha", "prisma", "eco", "visao", "selo_ruina", "dominio", "portal_impulso", "controlar_mente", "distorcer", "fagulha_incerta"], "cards": ["raio", "raio", "barreira", "barreira", "explosao", "explosao", "runas", "tempestade"]},
	"ladino": {"name": "Ladino", "hp": 29, "attack": 7, "power": 3, "armor": 1, "speed": 9, "type": "TECNICO", "sprite": "res://hero_rogue.png", "row": "front", "passive": "oportunista", "playable": true, "pool": ["punhal", "esquiva", "marca", "corrente", "sombra", "armadilha", "furto", "golpe_oculto", "corte_dreno", "queda", "jogo_sombras"], "cards": ["punhal", "punhal", "esquiva", "esquiva", "marca", "marca", "corrente", "sombra"]},
	"clerigo": {"name": "Clérigo", "hp": 32, "attack": 3, "power": 7, "armor": 2, "speed": 3, "type": "MENTAL", "sprite": "res://hero_cleric.png", "row": "back", "passive": "devocao", "playable": true, "pool": ["luz", "cura", "benção", "purificar", "julgamento", "abrigo", "fervor", "resgate", "campo_sagrado", "elo_vital", "benzer", "prisma_sangue", "balanca"], "cards": ["luz", "luz", "cura", "cura", "benção", "benção", "purificar", "julgamento"]},
	"paladino": {"name": "Paladino", "hp": 44, "attack": 6, "power": 5, "armor": 4, "speed": 2, "type": "PSICOLOGICO", "sprite": "res://hero_paladin.png", "row": "front", "passive": "baluarte", "playable": true, "pool": ["martelo", "egide", "provocar", "escudo_forte", "sentenca", "muralha_viva", "juramento", "brilho", "estandarte", "guarda_absoluta", "pele_rigida", "furia_total", "cerco_frente"], "cards": ["martelo", "martelo", "egide", "egide", "provocar", "provocar", "escudo_forte", "sentenca"]},
	"patrulheiro": {"name": "Patrulheiro", "hp": 31, "attack": 6, "power": 4, "armor": 1, "speed": 8, "type": "QUIMICO", "sprite": "res://hero_rogue.png", "row": "back", "passive": "rastreador", "playable": true, "pool": ["flecha", "foco", "salva", "rede", "veneno", "flanquear", "falcon", "chuva", "teia", "foco_ambiental", "predador", "armadilha_tempo", "agitar", "tiro_retaguarda"], "cards": ["flecha", "flecha", "foco", "foco", "salva", "rede", "veneno", "chuva"]},
	"fera": {"name": "Fera noturna", "hp": 13, "attack": 7, "power": 0, "armor": 0, "speed": 8, "type": "QUIMICO", "ai": "ASSASSINO", "sprite": "res://en_dog.png", "row": "front", "passive": "oportunista", "playable": false, "minion": true, "pool": ["punhal", "investida", "corte", "veneno", "marca", "furto", "sombra", "queda"], "cards": ["punhal", "punhal", "investida", "corte", "veneno", "marca", "furto", "sombra"]},
	"guardiao": {"name": "Guardião do Eclipse", "hp": 70, "attack": 8, "power": 8, "armor": 4, "speed": 3, "type": "MENTAL", "ai": "AGRESSIVO", "sprite": "res://en_elite.png", "row": "back", "passive": "canalizar", "playable": false, "minion": false, "boss": true, "pool": ["raio", "explosao", "tempestade", "julgamento", "selo_ruina", "brilho", "controlar_mente", "distorcer"], "cards": ["raio", "raio", "explosao", "tempestade", "julgamento", "brilho", "controlar_mente", "distorcer"]},
}

# Effects are applied in order. Each card is an action of its owner, never a summoned unit.
const CARDS := {
	"corte": {"name": "Corte firme", "class": "ATTACK", "target": "ENEMY", "reach": false, "gain": 1, "quick": true, "effects": [{"kind": "DAMAGE", "amount": 5, "stat": "attack"}]},
	"guarda": {"name": "Postura de guarda", "class": "SKILL", "target": "SELF", "gain": 1, "effects": [{"kind": "BLOCK", "amount": 10}, {"kind": "STATUS", "id": "counter", "duration": 1, "stacks": 1}]},
	"investida": {"name": "Investida de ferro", "class": "ATTACK", "target": "ENEMY", "reach": false, "gain": 1, "effects": [{"kind": "DAMAGE", "amount": 6, "stat": "attack"}, {"kind": "PUSH", "force": 2}]},
	"contra": {"name": "Resposta de aço", "class": "SKILL", "target": "SELF", "gain": 2, "effects": [{"kind": "STATUS", "id": "counter", "duration": 2, "stacks": 2}, {"kind": "BLOCK", "amount": 6}]},
	"furia": {"name": "Fúria disciplinada", "class": "POWER", "target": "ENEMY_ROW", "cost": 4, "effects": [{"kind": "DAMAGE", "amount": 9, "stat": "attack"}, {"kind": "STATUS", "id": "weak", "duration": 2, "stacks": 1}]},
	"raio": {"name": "Raio concentrado", "class": "ATTACK", "target": "ENEMY", "reach": true, "gain": 1, "effects": [{"kind": "DAMAGE", "amount": 5, "stat": "power"}]},
	"barreira": {"name": "Barreira arcana", "class": "SKILL", "target": "ALLY", "gain": 1, "effects": [{"kind": "SHIELD", "amount": 9}, {"kind": "STATUS", "id": "resist", "duration": 1, "stacks": 1}], "on_redraw": [{"kind": "SHIELD", "amount": 3}]},
	"explosao": {"name": "Detonação rúnica", "class": "POWER", "target": "ENEMY_ROW", "reach": true, "cost": 3, "effects": [{"kind": "DAMAGE", "amount": 7, "stat": "power"}]},
	"runas": {"name": "Runas móveis", "class": "SKILL", "target": "ALLY", "gain": 2, "effects": [{"kind": "MOVE", "row": "other"}, {"kind": "DRAW", "amount": 1}, {"kind": "GENERATE", "id": "centelha"}]},
	"tempestade": {"name": "Tempestade dos selos", "class": "POWER", "target": "ALL_ENEMIES", "reach": true, "cost": 5, "exhaust": true, "final": true, "effects": [{"kind": "DAMAGE", "amount": 6, "stat": "power"}, {"kind": "STATUS", "id": "stun", "duration": 1, "stacks": 1}]},
	"punhal": {"name": "Punhal veloz", "class": "ATTACK", "target": "ENEMY", "reach": false, "gain": 1, "quick": true, "effects": [{"kind": "DAMAGE", "amount": 4, "stat": "attack"}]},
	"esquiva": {"name": "Passo oculto", "class": "SKILL", "target": "SELF", "gain": 1, "effects": [{"kind": "STATUS", "id": "conceal", "duration": 1, "stacks": 1}, {"kind": "MOVE", "row": "other"}]},
	"marca": {"name": "Alvo exposto", "class": "SKILL", "target": "ENEMY", "reach": true, "gain": 2, "free": true, "effects": [{"kind": "STATUS", "id": "marked", "duration": 2, "stacks": 1}, {"kind": "STATUS", "id": "vulnerable", "duration": 1, "stacks": 1}]},
	"corrente": {"name": "Corte em sequência", "class": "ATTACK", "target": "CHAIN", "reach": true, "gain": 1, "chain": 3, "effects": [{"kind": "DAMAGE", "amount": 3, "stat": "attack"}], "full_combo": [{"kind": "STATUS", "id": "bleed", "duration": 2, "stacks": 2}]},
	"sombra": {"name": "Dança sombria", "class": "POWER", "target": "ENEMY", "reach": true, "cost": 3, "effects": [{"kind": "DAMAGE", "amount": 11, "stat": "attack"}, {"kind": "STATUS", "id": "bleed", "duration": 2, "stacks": 2}]},
	"luz": {"name": "Luz incisiva", "class": "ATTACK", "target": "ENEMY", "reach": true, "gain": 1, "effects": [{"kind": "DAMAGE", "amount": 4, "stat": "power"}]},
	"cura": {"name": "Cura vital", "class": "SKILL", "target": "ALLY", "gain": 1, "effects": [{"kind": "HEAL", "amount": 12}, {"kind": "CLEANSE", "ids": ["poison", "bleed", "burn"]}]},
	"benção": {"name": "Bênção persistente", "class": "SKILL", "target": "ALLY", "gain": 2, "effects": [{"kind": "STATUS", "id": "strengthened", "duration": 2, "stacks": 1}, {"kind": "STATUS", "id": "regen", "duration": 2, "stacks": 1}]},
	"purificar": {"name": "Purificação", "class": "SKILL", "target": "ALLY", "gain": 1, "free": true, "effects": [{"kind": "CLEANSE", "ids": ["poison", "bleed", "burn", "weak", "bind", "silence", "blind"]}, {"kind": "DRAW", "amount": 1}]},
	"julgamento": {"name": "Julgamento", "class": "POWER", "target": "ENEMY", "reach": true, "cost": 4, "effects": [{"kind": "DAMAGE", "amount": 10, "stat": "power"}, {"kind": "STATUS", "id": "stun", "duration": 1, "stacks": 1}]},
	"martelo": {"name": "Golpe de martelo", "class": "ATTACK", "target": "ENEMY", "gain": 1, "effects": [{"kind": "DAMAGE", "amount": 5, "stat": "attack"}, {"kind": "PULL"}]},
	"egide": {"name": "Égide", "class": "SKILL", "target": "ALLY", "gain": 1, "effects": [{"kind": "BLOCK", "amount": 8}, {"kind": "STATUS", "id": "armor", "duration": 2, "stacks": 1}]},
	"provocar": {"name": "Desafio", "class": "SKILL", "target": "SELF", "gain": 1, "effects": [{"kind": "STATUS", "id": "taunt", "duration": 2, "stacks": 1}, {"kind": "STATUS", "id": "counter", "duration": 1, "stacks": 1}]},
	"escudo_forte": {"name": "Muralha", "class": "SKILL", "target": "ALL_ALLIES", "gain": 2, "effects": [{"kind": "SHIELD", "amount": 6}, {"kind": "STATUS", "id": "barrier", "duration": 1, "stacks": 1}]},
	"sentenca": {"name": "Sentença", "class": "POWER", "target": "ENEMY", "cost": 5, "effects": [{"kind": "DAMAGE", "amount": 16, "stat": "attack", "pierce": true}]},
	"dueto": {"name": "Pacto de batalha", "class": "COMBO", "target": "ENEMY", "reach": true, "cost": 4, "exhaust": true, "effects": [{"kind": "DAMAGE", "amount": 18, "stat": "power"}, {"kind": "DRAW", "amount": 1}]},
	"golpe_largo": {"name": "Arco de aço", "class": "ATTACK", "target": "ENEMY_ROW", "gain": 1, "effects": [{"kind": "DAMAGE", "amount": 3, "stat": "attack"}]},
	"preparo": {"name": "Reunir forças", "class": "SKILL", "target": "SELF", "free": true, "gain": 1, "effects": [{"kind": "STATUS", "id": "strengthened", "duration": 2}, {"kind": "BLOCK", "amount": 4}]},
	"ruptura": {"name": "Quebra de escudo", "class": "POWER", "target": "ENEMY", "cost": 3, "effects": [{"kind": "DAMAGE", "amount": 10, "stat": "attack", "pierce": true}, {"kind": "STATUS", "id": "vulnerable", "duration": 1}]},
	"centelha": {"name": "Centelha", "class": "ATTACK", "target": "ENEMY", "reach": true, "quick": true, "gain": 1, "effects": [{"kind": "DAMAGE", "amount": 2, "stat": "power"}]},
	"prisma": {"name": "Prisma de defesa", "class": "SKILL", "target": "ALL_ALLIES", "cost": 2, "effects": [{"kind": "SHIELD", "amount": 5}]},
	"eco": {"name": "Eco arcano", "class": "SKILL", "target": "SELF", "gain": 2, "effects": [{"kind": "DRAW", "amount": 2}], "roulette": [{"kind": "SHIELD", "amount": 6}, {"kind": "STATUS", "id": "strengthened", "duration": 1}]},
	"armadilha": {"name": "Armadilha curta", "class": "SKILL", "target": "ENEMY", "reach": true, "gain": 1, "effects": [{"kind": "STATUS", "id": "bind", "duration": 2}, {"kind": "STATUS", "id": "weak", "duration": 1}]},
	"furto": {"name": "Furto veloz", "class": "ATTACK", "target": "ENEMY", "gain": 2, "effects": [{"kind": "DAMAGE", "amount": 2, "stat": "attack"}, {"kind": "DRAW", "amount": 1}]},
	"golpe_oculto": {"name": "Punhal nas sombras", "class": "POWER", "target": "ENEMY", "reach": true, "cost": 4, "effects": [{"kind": "DAMAGE", "amount": 13, "stat": "attack"}]},
	"abrigo": {"name": "Abrigo sagrado", "class": "SKILL", "target": "ALL_ALLIES", "cost": 2, "effects": [{"kind": "BLOCK", "amount": 5}, {"kind": "STATUS", "id": "resist", "duration": 1}]},
	"fervor": {"name": "Fervor", "class": "SKILL", "target": "ALLY", "free": true, "gain": 1, "effects": [{"kind": "STATUS", "id": "strengthened", "duration": 1}]},
	"resgate": {"name": "Resgate", "class": "SKILL", "target": "ALLY", "gain": 1, "effects": [{"kind": "HEAL", "amount": 7}, {"kind": "MOVE"}]},
	"muralha_viva": {"name": "Muralha viva", "class": "SKILL", "target": "SELF", "gain": 1, "effects": [{"kind": "BLOCK", "amount": 12}, {"kind": "STATUS", "id": "taunt", "duration": 1}]},
	"juramento": {"name": "Juramento de aço", "class": "SKILL", "target": "ALLY", "gain": 2, "effects": [{"kind": "SHIELD", "amount": 8}, {"kind": "CLEANSE", "ids": ["weak", "vulnerable"]}]},
	"brilho": {"name": "Clarão", "class": "ATTACK", "target": "ENEMY_ROW", "reach": true, "cost": 2, "effects": [{"kind": "DAMAGE", "amount": 4, "stat": "power"}, {"kind": "STATUS", "id": "blind", "duration": 1}]},
	"flecha": {"name": "Flecha certeira", "class": "ATTACK", "target": "ENEMY", "reach": true, "gain": 1, "effects": [{"kind": "DAMAGE", "amount": 5, "stat": "attack"}]},
	"foco": {"name": "Foco do caçador", "class": "SKILL", "target": "SELF", "gain": 2, "effects": [{"kind": "STATUS", "id": "strengthened", "duration": 1}, {"kind": "DRAW", "amount": 1}]},
	"salva": {"name": "Salva rente", "class": "ATTACK", "target": "ENEMY_ROW", "reach": true, "gain": 1, "effects": [{"kind": "DAMAGE", "amount": 3, "stat": "attack"}]},
	"rede": {"name": "Rede de caça", "class": "SKILL", "target": "ENEMY", "reach": true, "gain": 1, "effects": [{"kind": "STATUS", "id": "bind", "duration": 2}, {"kind": "PULL"}]},
	"veneno": {"name": "Flecha contaminada", "class": "ATTACK", "target": "ENEMY", "reach": true, "gain": 1, "effects": [{"kind": "DAMAGE", "amount": 2, "stat": "attack"}, {"kind": "STATUS", "id": "poison", "duration": 2, "stacks": 2}]},
	"flanquear": {"name": "Flanquear", "class": "SKILL", "target": "SELF", "free": true, "gain": 1, "effects": [{"kind": "MOVE"}, {"kind": "STATUS", "id": "conceal", "duration": 1}]},
	"falcon": {"name": "Olho da falcoaria", "class": "SKILL", "target": "ENEMY", "reach": true, "gain": 2, "effects": [{"kind": "STATUS", "id": "marked", "duration": 2}, {"kind": "DRAW", "amount": 1}]},
	"chuva": {"name": "Chuva de pontas", "class": "POWER", "target": "ALL_ENEMIES", "reach": true, "cost": 5, "effects": [{"kind": "DAMAGE", "amount": 4, "stat": "attack"}]},
	"frenesi_aco": {"name": "Frenesi de aço", "class": "SKILL", "target": "SELF", "gain": 2, "effects": [{"kind": "BLOCK", "amount": 9}, {"kind": "STATUS", "id": "bloodlust", "duration": 2}, {"kind": "STATUS", "id": "counter", "duration": 2}]},
	"martelo_pesado": {"name": "Martelo impulsor", "class": "ATTACK", "target": "ENEMY", "cost": 2, "effects": [{"kind": "DAMAGE", "amount": 6, "stat": "attack"}, {"kind": "PUSH", "force": 2, "forceful": true}]},
	"visao": {"name": "Visão do porvir", "class": "SKILL", "target": "SELF", "free": true, "effects": [{"kind": "STATUS", "id": "next_turn_plays", "duration": 2}, {"kind": "NEXT_TURN", "effects": [{"kind": "DRAW", "amount": 1}]}]},
	"selo_ruina": {"name": "Selo de ruína", "class": "POWER", "target": "ENEMY", "reach": true, "cost": 3, "effects": [{"kind": "STATUS", "id": "corrupted", "duration": 2}, {"kind": "STATUS", "id": "overload", "duration": 2}]},
	"corte_dreno": {"name": "Corte drenante", "class": "ATTACK", "target": "ENEMY", "gain": 1, "effects": [{"kind": "STATUS", "id": "lifesteal", "duration": 1, "self": true}, {"kind": "DAMAGE", "amount": 5, "stat": "attack"}, {"kind": "STATUS", "id": "wounded", "duration": 2}]},
	"queda": {"name": "Passagem perigosa", "class": "SKILL", "target": "ENEMY", "reach": true, "cost": 2, "effects": [{"kind": "STATUS", "id": "drop", "duration": 2}, {"kind": "PUSH", "force": 1}]},
	"campo_sagrado": {"name": "Campo sagrado", "class": "SKILL", "target": "SELF", "gain": 1, "effects": [{"kind": "STATUS", "id": "chaos_field", "duration": 2}, {"kind": "CURE"}]},
	"elo_vital": {"name": "Elo vital", "class": "SKILL", "target": "ALL_ALLIES", "cost": 2, "effects": [{"kind": "STATUS", "id": "soulbound", "duration": 2}, {"kind": "HEAL", "amount": 3}]},
	"estandarte": {"name": "Estandarte de defesa", "class": "SKILL", "target": "SELF", "cost": 2, "effects": [{"kind": "BLOCK", "amount": 15}, {"kind": "STATUS", "id": "binary", "duration": 2}, {"kind": "STATUS", "id": "protecting", "duration": 2}]},
	"guarda_absoluta": {"name": "Guarda absoluta", "class": "SKILL", "target": "ALLY", "gain": 1, "effects": [{"kind": "STATUS", "id": "protected", "duration": 1}, {"kind": "STATUS", "id": "invulnerable", "duration": 1}]},
	"teia": {"name": "Teia de caça", "class": "SKILL", "target": "ENEMY", "reach": true, "gain": 1, "effects": [{"kind": "STATUS", "id": "webbed_up", "duration": 2}, {"kind": "STATUS", "id": "bound", "duration": 1}]},
	"foco_ambiental": {"name": "Foco ambiental", "class": "SKILL", "target": "SELF", "gain": 1, "effects": [{"kind": "STATUS", "id": "opportunist", "duration": 2, "stacks": 2}, {"kind": "STATUS", "id": "perfect_aim", "duration": 2, "stacks": 2}]},
	"furia_totem": {"name": "Fúria do totem", "class": "SKILL", "target": "SELF", "cost": 2, "effects": [{"kind": "STATUS", "id": "en_fuego", "duration": 99}, {"kind": "STATUS", "id": "fury_totem", "duration": 2}, {"kind": "STATUS", "id": "fatal_fury", "duration": 1}]},
	"dominio": {"name": "Domínio do selo", "class": "SKILL", "target": "SELF", "gain": 1, "effects": [{"kind": "STATUS", "id": "enhanced", "duration": 2}, {"kind": "STATUS", "id": "fast", "duration": 2}, {"kind": "STATUS", "id": "unleashed", "duration": 2}, {"kind": "STATUS", "id": "portal", "duration": 2}, {"kind": "STATUS", "id": "neurally_enhanced", "duration": 2}]},
	"portal_impulso": {"name": "Impulso do selo", "class": "ATTACK", "target": "ENEMY", "reach": true, "gain": 1, "effects": [{"kind": "DAMAGE", "amount": 3, "stat": "power"}, {"kind": "PUSH", "force": 1}]},
	"controlar_mente": {"name": "Ruído mental", "class": "SKILL", "target": "ENEMY", "reach": true, "gain": 1, "effects": [{"kind": "STATUS", "id": "dazed", "duration": 2, "stacks": 2}, {"kind": "STATUS", "id": "slow", "duration": 2}]},
	"distorcer": {"name": "Distorcer vontade", "class": "SKILL", "target": "ENEMY", "reach": true, "gain": 1, "effects": [{"kind": "STATUS", "id": "confused", "duration": 2, "stacks": 2}]},
	"jogo_sombras": {"name": "Jogo de sombras", "class": "SKILL", "target": "SELF", "cost": 2, "effects": [{"kind": "STATUS", "id": "momentum", "duration": 1}, {"kind": "STATUS", "id": "critical", "duration": 1}, {"kind": "STATUS", "id": "berserk_lifesteal", "duration": 1}, {"kind": "STATUS", "id": "make_em_bleed", "duration": 2, "stacks": 2}]},
	"benzer": {"name": "Bênção do grupo", "class": "SKILL", "target": "ALL_ALLIES", "cost": 2, "effects": [{"kind": "STATUS", "id": "blessed", "duration": 2}, {"kind": "STATUS", "id": "all_together_now", "duration": 2, "stacks": 2}, {"kind": "STATUS", "id": "offensive_rush", "duration": 2}]},
	"prisma_sangue": {"name": "Prisma sanguíneo", "class": "SKILL", "target": "ALLY", "gain": 1, "effects": [{"kind": "STATUS", "id": "blood_magic", "duration": 2}, {"kind": "STATUS", "id": "vampiric_essence", "duration": 2}]},
	"pele_rigida": {"name": "Pele selada", "class": "SKILL", "target": "SELF", "gain": 1, "effects": [{"kind": "BLOCK", "amount": 10}, {"kind": "STATUS", "id": "symbiote_skin", "duration": 1}, {"kind": "STATUS", "id": "protecting", "duration": 1}]},
	"furia_total": {"name": "Força total", "class": "SKILL", "target": "SELF", "cost": 2, "effects": [{"kind": "STATUS", "id": "overpowered", "duration": 2}, {"kind": "STATUS", "id": "strongest_there_is", "duration": 2}]},
	"predador": {"name": "Instinto do predador", "class": "SKILL", "target": "SELF", "gain": 1, "effects": [{"kind": "STATUS", "id": "ravenous", "duration": 3, "stacks": 5}, {"kind": "STATUS", "id": "naturalist", "duration": 2}, {"kind": "STATUS", "id": "full_force", "duration": 2}]},
	"armadilha_tempo": {"name": "Laço instável", "class": "SKILL", "target": "ENEMY", "reach": true, "cost": 2, "effects": [{"kind": "STATUS", "id": "banished", "duration": 1}, {"kind": "STATUS", "id": "spike_bomb", "duration": 2}]},
	"agitar": {"name": "Agitação dirigida", "class": "SKILL", "target": "ENEMY", "reach": true, "gain": 1, "effects": [{"kind": "STATUS", "id": "berserk_enemy", "duration": 1}, {"kind": "STATUS", "id": "taunted", "duration": 1}]},
	"corte_adj": {"name": "Corte de flanco", "class": "ATTACK", "target": "ADJACENT", "rarity": "Incomum", "gain": 1, "effects": [{"kind": "DAMAGE", "amount": 3, "stat": "attack"}]},
	"fagulha_incerta": {"name": "Fagulha incerta", "class": "ATTACK", "target": "RANDOM", "rarity": "Incomum", "reach": true, "gain": 2, "effects": [{"kind": "DAMAGE", "amount": 8, "stat": "power"}]},
	"cerco_frente": {"name": "Cerco frontal", "class": "POWER", "target": "FRONT_ROW", "rarity": "Rara", "copy_limit": 1, "cost": 3, "effects": [{"kind": "DAMAGE", "amount": 5, "stat": "attack"}, {"kind": "STATUS", "id": "weak", "duration": 1}]},
	"tiro_retaguarda": {"name": "Disparo de retaguarda", "class": "POWER", "target": "BACK_ROW", "rarity": "Rara", "copy_limit": 1, "reach": true, "cost": 3, "effects": [{"kind": "DAMAGE", "amount": 8, "stat": "attack"}]},
	"balanca": {"name": "Balança de cinzas", "class": "SKILL", "target": "ANY_UNIT", "rarity": "Incomum", "reach": true, "gain": 1, "effects": [{"kind": "HEAL", "amount": 8}, {"kind": "STATUS", "id": "weak", "duration": 1}]},
}

const ENEMIES := {
	"soldado": {"name": "Sentinela", "hp": 19, "attack": 5, "power": 1, "armor": 2, "speed": 5, "type": "BRUTO", "ai": "DEFENSIVO", "sprite": "res://en_elite.png", "row": "front", "skills": ["strike", "guard"]},
	"arqueiro": {"name": "Batedor", "hp": 16, "attack": 5, "power": 2, "armor": 1, "speed": 7, "type": "PROJETIVO", "sprite": "res://en_sniper.png", "row": "back", "skills": ["shot", "poison_shot"]},
	"fera": {"name": "Fera noturna", "hp": 13, "attack": 7, "power": 0, "armor": 0, "speed": 8, "type": "QUIMICO", "ai": "ASSASSINO", "sprite": "res://en_dog.png", "row": "front", "minion": true, "skills": ["strike"]},
	"elite": {"name": "Capitão da Vigília", "hp": 35, "attack": 7, "power": 4, "armor": 4, "speed": 4, "type": "TECNICO", "ai": "DEFENSIVO", "sprite": "res://en_elite.png", "row": "front", "elite": true, "skills": ["strike", "guard", "sweep"]},
	"boss": {"name": "Guardião do Eclipse", "hp": 70, "attack": 8, "power": 8, "armor": 4, "speed": 3, "type": "MENTAL", "faction": "abissal", "sprite": "res://en_elite.png", "row": "back", "boss": true, "skills": ["shot", "sweep", "ritual"]},
	"batedor": {"name": "Escaramuçador", "hp": 18, "attack": 6, "power": 1, "armor": 0, "speed": 9, "type": "TECNICO", "ai": "ASSASSINO", "sprite": "res://en_sniper.png", "row": "front", "skills": ["strike", "poison_shot"]},
	"ocultista": {"name": "Ocultista", "hp": 22, "attack": 2, "power": 7, "armor": 1, "speed": 4, "type": "MENTAL", "sprite": "res://en_sniper.png", "row": "back", "skills": ["ritual", "shot", "invocacao"]},
	"brutamontes": {"name": "Brutamontes", "hp": 28, "attack": 8, "power": 0, "armor": 3, "speed": 2, "type": "BRUTO", "ai": "AGRESSIVO", "sprite": "res://en_elite.png", "row": "front", "skills": ["strike", "sweep"]},
	"carrasco": {"name": "Carrasco", "hp": 24, "attack": 7, "power": 1, "armor": 1, "speed": 5, "type": "PSICOLOGICO", "sprite": "res://en_elite.png", "row": "front", "skills": ["strike", "ritual", "transe", "fome"]},
	"alquimista": {"name": "Alquimista", "hp": 19, "attack": 3, "power": 6, "armor": 1, "speed": 6, "type": "QUIMICO", "sprite": "res://en_sniper.png", "row": "back", "skills": ["poison_shot", "guard"]},
	"vigia": {"name": "Vigia", "hp": 18, "attack": 5, "power": 1, "armor": 2, "speed": 6, "type": "PROJETIVO", "sprite": "res://en_sniper.png", "row": "back", "skills": ["shot", "guard"]},
	"sombrio": {"name": "Acólito sombrio", "hp": 16, "attack": 4, "power": 4, "armor": 0, "speed": 7, "type": "MENTAL", "faction": "abissal", "sprite": "res://en_dog.png", "row": "front", "skills": ["ritual", "strike"]},
	"elite_alquimista": {"name": "Mestre dos Venenos", "hp": 40, "attack": 5, "power": 8, "armor": 3, "speed": 6, "type": "QUIMICO", "sprite": "res://en_elite.png", "row": "back", "elite": true, "skills": ["poison_shot", "ritual", "guard"]},
	"elite_bruto": {"name": "General de Ferro", "hp": 48, "attack": 10, "power": 2, "armor": 5, "speed": 3, "type": "BRUTO", "ai": "DEFENSIVO", "sprite": "res://en_elite.png", "row": "front", "elite": true, "skills": ["strike", "sweep", "guard", "espinhos"]},
}

const ENEMY_CARDS := {
	"strike": {"name": "Ataque", "target": "ENEMY", "effects": [{"kind": "DAMAGE", "amount": 4, "stat": "attack"}]},
	"shot": {"name": "Disparo", "target": "ENEMY", "reach": true, "effects": [{"kind": "DAMAGE", "amount": 4, "stat": "attack"}]},
	"poison_shot": {"name": "Dardo tóxico", "target": "ENEMY", "reach": true, "effects": [{"kind": "DAMAGE", "amount": 2, "stat": "attack"}, {"kind": "STATUS", "id": "poison", "duration": 2, "stacks": 1}, {"kind": "INFECT"}]},
	"guard": {"name": "Guarda", "target": "SELF", "effects": [{"kind": "BLOCK", "amount": 7}]},
	"sweep": {"name": "Varredura", "target": "ENEMY_ROW", "reach": true, "effects": [{"kind": "DAMAGE", "amount": 4, "stat": "attack"}]},
	"ritual": {"name": "Selo adverso", "target": "ENEMY", "reach": true, "effects": [{"kind": "DAMAGE", "amount": 5, "stat": "power"}, {"kind": "STATUS", "id": "weak", "duration": 2, "stacks": 1}]},
	"invocacao": {"name": "Círculo instável", "target": "SELF", "priority": 19, "effects": [{"kind": "STATUS", "id": "summoning", "duration": 2}]},
	"transe": {"name": "Transe de guerra", "target": "SELF", "priority": 17, "effects": [{"kind": "STATUS", "id": "frenzy", "duration": 2, "stacks": 2}]},
	"fome": {"name": "Caça ao objetivo", "target": "SELF", "priority": 15, "objective": "PROTECT", "effects": [{"kind": "STATUS", "id": "feeding_frenzy", "duration": 2, "stacks": 3}]},
	"espinhos": {"name": "Pele espinhosa", "target": "SELF", "priority": 16, "effects": [{"kind": "STATUS", "id": "symbiote_skin", "duration": 1}, {"kind": "BLOCK", "amount": 6}]},
}

const MISSIONS := {
	"road": {"name": "Estrada abandonada", "objective": "ELIMINATE", "enemies": ["paladino", "ladino", "patrulheiro"], "reinforcements": {3: ["fera", "fera"]}, "environment": [{"name": "Coluna rachada", "cost": 2, "damage": 6, "target": "front"}]},
	"ritual": {"name": "Círculo de cinzas", "objective": "SURVIVE", "turns": 5, "enemies": ["guerreiro", "mago", "clerigo"], "reinforcements": {3: ["fera"]}, "environment": [{"name": "Runa instável", "cost": 2, "status": "vulnerable", "target": "back"}]},
	"watch": {"name": "Defesa da sentinela", "objective": "PROTECT", "turns": 4, "protect_hp": 40, "enemies": ["ladino", "patrulheiro", "guerreiro"], "reinforcements": {2: ["fera"]}, "environment": [{"name": "Cristal de vigília", "cost": 2, "heal": 8, "target": "ally"}]},
	"eclipse": {"name": "Guardião do Eclipse", "objective": "BOSS", "enemies": ["guardiao", "mago", "ladino"], "reinforcements": {3: ["fera", "fera"]}, "environment": [{"name": "Pilar selado", "cost": 3, "damage": 9, "target": "back"}]},
}

# Campaign order does not change the combat data: mission identifiers remain stable in saves.
const CAMPAIGN := {
	"road": {"requires": [], "par": 4, "brief": "Paladino, Ladino e Patrulheiro bloqueiam a estrada. Elimine a patrulha; feras chegam na terceira rodada.", "goal": "Elimine inimigos e reforços."},
	"ritual": {"requires": ["road"], "par": 5, "brief": "O círculo permanece ativo por cinco rodadas. Guerreiro, Mago e Clérigo mantêm o selo enquanto a runa expõe a retaguarda.", "goal": "Resista por cinco rodadas."},
	"watch": {"requires": ["road"], "par": 4, "brief": "Defenda a sentinela até a quarta rodada. Uma fera entra na segunda rodada.", "goal": "Proteja a sentinela por quatro rodadas."},
	"eclipse": {"requires": ["ritual", "watch"], "par": 6, "brief": "O Guardião do Eclipse ocupa a retaguarda, com Mago e Ladino. Reduza sua vida à metade para expor a segunda fase.", "goal": "Derrote o Guardião do Eclipse."},
}

const HERO_LORE := {
	"guerreiro": {"role": "Vanguarda", "trait": "Na frente recebe 2 de Bloqueio no começo de cada rodada.", "history": "Ex-sentinela que abandonou a Vigília após a queda da estrada."},
	"mago": {"role": "Artilharia", "trait": "Canalizar gera 1 Iniciativa a cada rodada.", "history": "Estudou os selos que alimentam o ritual de cinzas."},
	"ladino": {"role": "Execução", "trait": "Causa dano extra a alvos marcados.", "history": "Contrabandista que conhece as rotas entre os postos da Vigília."},
	"clerigo": {"role": "Sustento", "trait": "Amplia a cura das habilidades.", "history": "Guardião das últimas sentinelas que resistem à corrupção."},
	"paladino": {"role": "Proteção", "trait": "Recebe 2 de Escudo a cada rodada.", "history": "Jurou manter o círculo de cinzas fechado."},
	"patrulheiro": {"role": "Controle", "trait": "Ataca melhor da retaguarda.", "history": "Rastreia os reforços que atravessam a estrada abandonada."},
	"fera": {"role": "Minion", "trait": "Pode haver mais de uma fera no mesmo lado. Não entra no grupo do jogador.", "history": "Caça em matilha. O código marca minion para permitir cópias."},
	"guardiao": {"role": "Chefe", "trait": "Na segunda fase o lado adversário ganha uma ação extra. Não pode ser escolhido pelo jogador.", "history": "O eclipse anda com as mesmas cartas dos heróis, só que do outro lado da arena."},
}
